name: Deploy Flask App

on:
  push:
    branches:
      - main
      - ma_nouvelle_branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy application
        run: |
          echo "Déploiement automatique pour la branche ${{ github.ref }}"
